version: '2'
services:
  backendchallenge-app:
    image: backendchallenge
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://backendchallenge-postgresql:5432/backendchallenge
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  backendchallenge-postgresql:
    extends:
      file: postgresql.yml
      service: backendchallenge-postgresql
